services:
    aircraft_manufacturing:
        build:
            context: ../
            dockerfile: ./deploy/Dockerfile
        image: aircraft_manufacturing:latest
        volumes:
            - static_volume:/src/frontend/static
            - management_volume:/src/management # Volume for management/scripts/init.sh script, remove it if you have to run it again
        environment:
            - DJANGO_SETTINGS_MODULE=aircraft_manufacturing.settings.production
            - POSTGRES_DB=${POSTGRES_DB:-aircraft_db}
            - POSTGRES_USER=${POSTGRES_USER:-postgres}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
            - POSTGRES_HOST=db
            - POSTGRES_PORT=5432
        depends_on:
            - db
        networks:
            - aircraft-network

    db:
        image: postgres:17.2
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=${POSTGRES_DB:-aircraft_db}
            - POSTGRES_USER=${POSTGRES_USER:-postgres}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
        networks:
            - aircraft-network

    nginx:
        image: nginx:1.27.3
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - static_volume:/src/frontend/static
        ports:
            - "8000:80" # Host'ta 8000 portundan nginx'in 80 portuna yönlendirme
        depends_on:
            - aircraft_manufacturing
        networks:
            - aircraft-network

volumes:
    postgres_data:
    static_volume:
    management_volume:

networks:
    aircraft-network:
        driver: bridge
